import { CompactType, DirTypes, DisplayGrid, GridType } from 'angular-gridster2';

export const gridsterConfig = {
  gridType: GridType.ScrollVertical,
  compactType: CompactType.CompactUp,
  margin: 22,
  outerMargin: true,
  outerMarginTop: 16,
  outerMarginRight: 16,
  outerMarginBottom: 16,
  outerMarginLeft: 22,
  useTransformPositioning: true,
  setGridSize: true,
  mobileBreakpoint: 991,
  minCols: 16,
  maxCols: 24,
  minRows: 6,
  maxRows: 100,
  maxItemCols: 24,
  minItemCols: 8,
  maxItemRows: 24,
  minItemRows: 8,
  maxItemArea: 2500,
  minItemArea: 1,
  defaultItemCols: 16,
  defaultItemRows: 8,
  fixedColWidth: 105,
  fixedRowHeight: 105,
  keepFixedHeightInMobile: false,
  keepFixedWidthInMobile: false,
  scrollSensitivity: 100,
  scrollSpeed: 100,
  enableEmptyCellClick: false,
  enableEmptyCellContextMenu: false,
  enableEmptyCellDrop: false,
  enableEmptyCellDrag: false,
  emptyCellDragMaxCols: 50,
  emptyCellDragMaxRows: 50,
  ignoreMarginInRow: false,
  draggable: {
    enabled: true,
    dropOverItems: false,
  },
  resizable: {
    enabled: true,
    handles: {
      s: true,
      e: true,
      n: true,
      w: true,
      se: true,
      ne: true,
      sw: true,
      nw: true,
    },
  },
  swap: true,
  swapWhileDragging: true,
  pushItems: true,
  disablePushOnDrag: false,
  disablePushOnResize: false,
  pushDirections: {
    north: true,
    east: true,
    south: true,
    west: true,
  },
  pushResizeItems: true,
  displayGrid: DisplayGrid.None,
  disableWindowResize: false,
  disableWarnings: false,
  scrollToNewItems: false,
  dirType: DirTypes.LTR,
};
