import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class CashflowForecastService {
  selectedCurrency: string;

  forecastPeriod: string;
  selectedForecastPeriodOption: string = 'This Month';

  cashflowTransactionsRowData: any[] = [
    {
      id: '01',
      source: ['Opening Balance'],
      valueDate: '01-Oct-2024',
      transactionNarration: '',
      benificiary: '',
      withdrawals: '',
      deposited: '',
      balance: '400000',
      moreActions: false,
    },
    {
      id: '02',
      source: ['Actual Transactions'],
      valueDate: '',
      transactionNarration: '',
      benificiary: '',
      withdrawals: '',
      deposited: '',
      balance: '',
      moreActions: false,
    },
    {
      id: '03',
      source: ['Actual Transactions', 'CBS'],
      valueDate: '02-Oct-2024',
      transactionNarration: '',
      benificiary: '',
      withdrawals: '56600',
      deposited: '',
      balance: '343400',
      moreActions: false,
    },
    {
      id: '04',
      source: ['Actual Transactions', 'CBS '],
      valueDate: '03-Oct-2024',
      transactionNarration: '',
      benificiary: '',
      withdrawals: '15400',
      deposited: '',
      balance: '328000',
      moreActions: false,
    },
    {
      id: '05',
      source: ['Actual Transactions', 'CBS  '],
      valueDate: '04-Oct-2024',
      transactionNarration: '',
      benificiary: '',
      withdrawals: '',
      deposited: '12930',
      balance: '340930',
      moreActions: false,
    },
    {
      id: '06',
      source: ['Actual Transactions', 'CBS   '],
      valueDate: '05-Oct-2024',
      transactionNarration: '',
      benificiary: '',
      withdrawals: '',
      deposited: '159070',
      balance: '500000',
      moreActions: false,
    },
    {
      id: '07',
      source: ['Manual Entry - One Time'],
      valueDate: '08-Oct-2024',
      transactionNarration: 'Invoice Finance EMI',
      benificiary: 'Ms ABC',
      withdrawals: '50000',
      deposited: '',
      balance: '450000',
      moreActions: false,
    },
    {
      id: '08',
      source: ['Collection'],
      valueDate: '09-Oct-2024',
      transactionNarration: 'Cheque Deposit',
      benificiary: 'John Miller',
      withdrawals: '',
      deposited: '100000',
      balance: '550000',
      forecastAs: 'Inward Payment',
      entryType: 'One Time',
      narration: '23',
      lockRecord: false,
      description: '123',
      mode: '',
      accountType: 'Internal Account',
      accountNumber: '1600',
      forecastedAmountCCY: '1',
      forecastedAmount: '12',
      recurringFrom: '',
      recurringTo: '',
      recurrencePattern: '',
      requestBy: 'CORPORATE',
      corporateId: 100083,
      corporateCode: '999200',
      corporateName: 'Toyota Motors',
      eodBod: '',
      days: '',
      date: '',
      moreActions: true
    },
    {
      id: '09',
      source: ['Payment'],
      valueDate: '10-Oct-2024',
      transactionNarration: 'Invoice Finance EMI',
      benificiary: 'Ms ABC',
      withdrawals: '30000',
      deposited: '',
      balance: '520000',
      forecastAs: 'Inward Payment',
      entryType: 'One Time',
      narration: '23',
      lockRecord: false,
      description: '123',
      mode: '',
      accountType: 'Internal Account',
      accountNumber: '1600',
      forecastedAmountCCY: '1',
      forecastedAmount: '12',
      recurringFrom: '',
      recurringTo: '',
      recurrencePattern: '',
      requestBy: 'CORPORATE',
      corporateId: 100083,
      corporateCode: '999200',
      corporateName: 'Toyota Motors',
      eodBod: '',
      days: '',
      date: '',
      moreActions: true,
    },
    {
      id: '10',
      source: ['Collection '],
      valueDate: '11-Oct-2024',
      transactionNarration: 'Cheque Deposit',
      benificiary: 'John Miller',
      withdrawals: '',
      deposited: '50000',
      balance: '570000',
      forecastAs: 'Inward Payment',
      entryType: 'One Time',
      narration: '23',
      lockRecord: false,
      description: '123',
      mode: '',
      accountType: 'Internal Account',
      accountNumber: '1600',
      forecastedAmountCCY: '1',
      forecastedAmount: '12',
      recurringFrom: '',
      recurringTo: '',
      recurrencePattern: '',
      requestBy: 'CORPORATE',
      corporateId: 100083,
      corporateCode: '999200',
      corporateName: 'Toyota Motors',
      eodBod: '',
      days: '',
      date: '',
      moreActions: true,
    },
    {
      id: '11',
      source: ['Manual Entry - One Time '],
      valueDate: '24-Oct-2024',
      transactionNarration: 'Invoice Finance EMI',
      benificiary: 'Ms ABC',
      withdrawals: '20000',
      deposited: '',
      balance: '550000',
      forecastAs: 'Inward Payment',
      entryType: 'One Time',
      narration: '23',
      lockRecord: false,
      description: '123',
      mode: '',
      accountType: 'Internal Account',
      accountNumber: '1600',
      forecastedAmountCCY: '1',
      forecastedAmount: '12',
      recurringFrom: '',
      recurringTo: '',
      recurrencePattern: '',
      requestBy: 'CORPORATE',
      corporateId: 100083,
      corporateCode: '999200',
      corporateName: 'Toyota Motors',
      eodBod: '',
      days: '',
      date: '',
      moreActions: true,
    },
    {
      id: '12',
      source: ['Collection  '],
      valueDate: '25-Oct-2024',
      transactionNarration: 'Cheque Deposit',
      benificiary: 'John Miller',
      withdrawals: '',
      deposited: '50000',
      balance: '600000',
      forecastAs: 'Inward Payment',
      entryType: 'One Time',
      narration: '23',
      lockRecord: false,
      description: '123',
      mode: '',
      accountType: 'Internal Account',
      accountNumber: '1600',
      forecastedAmountCCY: '1',
      forecastedAmount: '12',
      recurringFrom: '',
      recurringTo: '',
      recurrencePattern: '',
      requestBy: 'CORPORATE',
      corporateId: 100083,
      corporateCode: '999200',
      corporateName: 'Toyota Motors',
      eodBod: '',
      days: '',
      date: '',
      moreActions: true,
    },
  ];

  cashflowIgnoredTransactionsRowData: any[] = [
    {
      id: '07',
      source: ['Manual Entry - One Time'],
      valueDate: '10-Oct-2024',
      transactionNarration: 'Invoice Finance EMI',
      benificiary: 'Ms ABC',
      withdrawals: '1550.60',
      deposited: '',
      balance: '15920.40',
      moreActions: false,
    },
    {
      id: '08',
      source: ['Collection'],
      valueDate: '10-Oct-2024',
      transactionNarration: 'Cheque Deposit',
      benificiary: 'John Miller',
      withdrawals: '',
      deposited: '9210',
      balance: '25130',
      moreActions: true,
    },
    {
      id: '09',
      source: ['Payment'],
      valueDate: '10-Oct-2024',
      transactionNarration: 'Invoice Finance EMI',
      benificiary: 'Ms ABC',
      withdrawals: '1550.60',
      deposited: '',
      balance: '15920.40',
      moreActions: true,
    },
    {
      id: '10',
      source: ['Collection '],
      valueDate: '10-Oct-2024',
      transactionNarration: 'Cheque Deposit',
      benificiary: 'John Miller',
      withdrawals: '',
      deposited: '9210',
      balance: '25130',
      moreActions: true,
    },
    {
      id: '11',
      source: ['Manual Entry - One Time '],
      valueDate: '10-Oct-2024',
      transactionNarration: 'Finance Repayment',
      benificiary: '',
      withdrawals: '31000',
      deposited: '',
      balance: '-5930',
      moreActions: true,
    },
    {
      id: '12',
      source: ['Collection  '],
      valueDate: '10-Oct-2024',
      transactionNarration: 'Cheque Deposit',
      benificiary: 'John Miller',
      withdrawals: '',
      deposited: '7800',
      balance: '1870.10',
      moreActions: true,
    },
  ];

  accounts: any[] = [
    {
      accountBranch: "Down Town Branch",
      accountDesc: "Business Checking Account",
      accountNo: "777000003002",
      accountNumber: "777000003002-SAR",
      accountTitle: "Business Checking Account",
      accountType: "CURRENT",
      active: "Y",
      amountApproved: 1575002,
      amountDisbursed: 152502,
      authorized: "Y",
      availableBalance: 5100000,
      balance: 15100000,
      bank: "CIMB",
      bankAccountType: "CONVENTIONAL",
      cashFlowForecastOverview: "Cash Flow",
      cashInFlowDistributionChartData: [
        { /* Data 1 */ },
        { /* Data 2 */ },
        { /* Data 3 */ },
        { /* Data 4 */ },
        { /* Data 5 */ }
      ],
      cashInFlowDistributionChartOptions: {
        data: [
          /* Data */
        ],
        labelKey: 'label',
        angleKey: 'value',
        formatter: function () { /* Formatter Function */ }
      },
      cashOutFlowDistributionChartData: [
        { /* Data 1 */ },
        { /* Data 2 */ },
        { /* Data 3 */ },
        { /* Data 4 */ },
        { /* Data 5 */ }
      ],
      cashOutFlowDistributionChartOptions: {
        data: [
          /* Data */
        ],
        labelKey: 'label',
        angleKey: 'value',
        formatter: function () { /* Formatter Function */ }
      },
      cashflowAccount: "Y",
      cashflowChartData: [
        { /* Data 1 */ },
        { /* Data 2 */ },
        { /* Data 3 */ }
      ],
      cashflowChartOptions: {
        data: [
          /* Data */
        ],
        legend: { /* Legend Data */ },
        series: [
          /* Series Data */
        ],
        axes: [
          /* Axes Data */
        ]
      },
      cashflowData: [
        { /* Data 1 */ },
        { /* Data 2 */ },
        { /* Data 3 */ },
        { /* Data 4 */ },
        { /* Data 5 */ },
        { /* Data 6 */ },
        { /* Data 7 */ },
        { /* Data 8 */ },
        { /* Data 9 */ },
        { /* Data 10 */ }
      ],
      cashflowGridData: [
        { /* Data 1 */ },
        { /* Data 2 */ },
        { /* Data 3 */ }
      ],
      checkedBy: "adminchecker",
      checkedOn: 44140,
      checkedSysOn: 44525.6722800926,
      closingBalance: 57036,
      corporateAccountAlias: "Business Checking Account",
      country: "MYS",
      currencyCode: "USD",
      currencyId: 1,
      enabled: "Y",
      grantedDate: 44142,
      holdBalance: 200000,
      id: 1600,
      ladgerBalance: 850000,
      lastAction: "create Authorized",
      ledgerBalance: 5100000,
      maturityDate: 45968,
      modifiedAtOU: 11,
      modifiedBy: "adminmaker",
      modifiedOn: 44140,
      modifiedSysOn: 44525.6719791667,
      monthlyAvailableBalance: 1725000,
      mstId: 100083,
      odLimit: 700000,
      openingBalance: 54995,
      optionType: "Monthly",
      outstandingAmount: 10002,
      overdueAmount: 15002,
      product: "A",
      show: false,
      status: "Active",
      tenor: 77,
      totalCashInFlow: 222302,
      totalCashOutFlow: 239180,
      totalCreditBalance: "600000",
      totalDebitBalance: 950000,
      totalNetInFlow: 45267,
      totalPayable: 600000,
      totalReceivable: 950000,
      unclearBalance: 1500,
      version: 3
    }
  ];

  selectedAccount: any;

  insights: any[] = [
    {
      icon: 'fa-level-up-alt',
      class: 'text-color-success',
      label: 'AE611234958209401190202- INR Account has High cashflow for-Oct-2024',
    },

    {
      icon: 'fa-level-down-alt',
      class: 'text-color-danger',
      label: 'AE611234958209401190202- INR Account has Low cashflow for DEC 2024.',
    },
    {
      icon: 'fa-level-up-alt',
      class: 'text-color-success',
      label: 'AE611234958209401190202- INR Account has High cashflow for-Oct-2024',
    },

    {
      icon: 'fa-level-down-alt',
      class: 'text-color-danger',
      label: 'AE611234958209401190202- INR Account has Low cashflow for DEC 2024.',
    },
  ];

  constructor() { }

  getAccountInfo(accountNumber: string) {
    return this.accounts.find((account: any) => account.accountNumber == accountNumber);
  }
}
