export class AccessibilityConfig {
  isInterfaceEnabled: boolean;
  isDyslexiaFriendly: boolean;
  dyslexiaFriendly: number;
  isSeizerSafeProfile: boolean;
  isVisionImpairedProfile: boolean;
  isCognitiveDisabilityProfile: boolean;
  contentScalingBy: number;
  isHightlightTitles: boolean;
  isHightlightLinks: boolean;
  isReadableFont: boolean;
  adjustFontSizeBy: number;
  isAlignCenter: boolean;
  lineHeightBy: number;
  isAlignLeft: boolean;
  letterSpacingBy: number;
  isAlignRight: boolean;
  isDarkContrast: boolean;
  isLightContrast: boolean;
  isMonochrome: boolean;
  isHighSaturation: boolean;
  isHighContrast: boolean;
  textColor: string;
  titleColor: string;
  isHideImage: boolean;
  isReadingGuide: boolean;
  isReadingMask: boolean;
  isBigBlackCursor: boolean;
  isBigWhiteCursor: boolean;
  iconTop: string;
  iconLeft: string;
  constructor() {
    this.isInterfaceEnabled = true;
    this.isSeizerSafeProfile = false;
    this.isVisionImpairedProfile = false;
    this.isCognitiveDisabilityProfile = false;
    this.isReadableFont = false;
    this.contentScalingBy = 0;
    this.isHightlightTitles = false;
    this.isHightlightLinks = false;
    this.dyslexiaFriendly = 0;
    this.isDyslexiaFriendly = false;
    this.adjustFontSizeBy = 0;
    this.isAlignCenter = false;
    this.lineHeightBy = 0;
    this.isAlignLeft = false;
    this.letterSpacingBy = 0;
    this.isAlignRight = false;
    this.isDarkContrast = true;
    this.isLightContrast = false;
    this.isMonochrome = false;
    this.isHighSaturation = false;
    this.isHighContrast = false;
    this.textColor = '';
    this.titleColor = '';
    this.isHideImage = false;
    this.isReadingGuide = false;
    this.isReadingMask = false;
    this.isBigBlackCursor = false;
    this.isBigWhiteCursor = false;
    this.iconTop = window.innerHeight - 100 + 'px'; // 'calc(100vh - 100px)';
    this.iconLeft = window.innerWidth - 60 + 'px'; //'calc(100vw - 60px)';
  }
}
export const DYSLEXIA_FONT_FAMILY_LIST: string[] = ['Airial', 'Calibri', 'Verdana'];
