export class OatSiManagement {
  public remarks?: string;
  public isShow?: boolean;
  public channelName?: string;
  public corporateCode?: string;
  public corporateRefNo?: string;
  public transactionDate?: string;
  public valueDate?: string;
  public uploadStatus?: string;
  public corporateProductId?: string;
  public isPaperBasedTransaction?: boolean;
  public paymentMethodId?: string;
  public paymentMethodName?: string;
  public debitAccountId?: string;
  public debitAccountCorporate?: string;
  public debitCurrencyId?: string;
  public debitCurrencyCode?: string;
  public debitAmount?: string;
  public payableCurrencyId?: string;
  public payableCurrencyCode?: string;
  public creditAccountId?: string;
  public creditAccountCorporate?: string;
  public creditCurrencyId?: string;
  public bank?: string;
  public creditCurrencyCode?: string;
  public creditAmount?: string;
  public payableAmount?: string;
  public totalRequest?: string;
  public totalRequestAmount?: string;
  public beneficiaryName?: string;
  public payableFxRate?: string;
  public fxRate?: string;
  public debitFxRate?: string;
  public entryType?: string;
  public entryMode?: string;
  public requestBy?: string;
  public initiateMode?: string;
  public debitAccountNo?: string;
  public debitAccountBalance?: string;
  public creditAccountNo?: string;
  public creditAccountBalance?: string;
  public remark?: string;
  public accountTitle?: string;
  public status?: string;
  public siName?: string;
  public remittancePurpose?: string;
  public oatSiManagementDetails?: OatSiManagementDetail[];
  public siDetails?: SiDetails[];
  constructor() {
    this.remarks = '';
    this.isShow = false;
    this.channelName = '';
    this.corporateCode = '';
    this.corporateRefNo = '';
    this.transactionDate = '';
    this.valueDate = '';
    this.uploadStatus = '';
    this.corporateProductId = '';
    this.isPaperBasedTransaction = false;
    this.paymentMethodId = '';
    this.paymentMethodName = '';
    this.debitAccountId = '';
    this.debitAccountCorporate = '';
    this.debitCurrencyId = '';
    this.debitCurrencyCode = '';
    this.debitAmount = '';
    this.payableCurrencyId = '';
    this.payableCurrencyCode = '';
    this.creditAccountId = '';
    this.creditAccountCorporate = '';
    this.creditCurrencyId = '';
    this.bank = '';
    this.creditCurrencyCode = '';
    this.creditAmount = '';
    this.payableAmount = '';
    this.totalRequest = '';
    this.totalRequestAmount = '';
    this.beneficiaryName = '';
    this.payableFxRate = '';
    this.fxRate = '';
    this.debitFxRate = '';
    this.entryType = '';
    this.entryMode = '';
    this.requestBy = '';
    this.initiateMode = '';
    this.debitAccountNo = '';
    this.debitAccountBalance = '';
    this.creditAccountNo = '';
    this.creditAccountBalance = '';
    this.remark = '';
    this.accountTitle = '';
    this.status = '';
    this.siName = '';
    this.remittancePurpose = '';
    this.oatSiManagementDetails = [new OatSiManagementDetail()];
    this.siDetails = [new SiDetails()];
  }
}

export class SiDetails {
  public name?: string;
  public authorization?: string;
  public startDate?: string;
  public endDate?: string;
  public frequency?: string;
  public frequencyDetails?: string;
  public ifHoliday?: string;
  constructor() {
    this.name = '';
    this.authorization = 'NO';
    this.startDate = '';
    this.endDate = '';
    this.frequency = '';
    this.frequencyDetails = '';
    this.ifHoliday = 'Prepone';
  }
}

export class OatSiManagementDetail {
  public beneficiaryId?: string;
  public beneficiaryCode?: string;
  public beneficiaryName?: string;
  public beneficiaryType?: string;
  public accountNo?: string;
  public payeeName?: string;
  public beneficiaryAddress1?: string;
  public beneficiaryAddress2?: string;
  public beneficiaryAddress3?: string;
  public city?: string;
  public locationId?: string;
  public stateId?: string;
  public countryId?: string;
  public pinCode?: string;
  public phoneNo?: string;
  public faxNo?: string;
  public email?: string;
  public paymentMethodId?: string;
  public debitCurrencyId?: string;
  public payableCurrencyId?: string;
  public corporateProductId?: string;
  public isPaperBasedTransaction?: boolean;
  public debitAmount?: string;
  public payableAmount?: string;
  public valueDate?: string;
  public transactionDate?: string;
  public debitAccountId?: string;
  public paymentDetails1?: string;
  public paymentDetails2?: string;
  public paymentDetails3?: string;
  public paymentDetails4?: string;
  public corporateRefNo?: string;
  public paymentType?: string;
  public amountType?: string;
  public exchangeType?: string;
  public dealNo?: string;
  public forwardExchangeId?: string;
  public supportingDocList?: any;
  public enrichments?: any;
  public remarks?: string;
  public creditAccountId?: string;
  public creditCurrencyId?: string;
  public oatSiManagementAdditionalDetail?: OatSiManagementAdditionalDetail[];

  constructor() {
    this.beneficiaryId = '';
    this.beneficiaryCode = '';
    this.beneficiaryName = '';
    this.beneficiaryType = '';
    this.accountNo = '';
    this.payeeName = '';
    this.beneficiaryAddress1 = '';
    this.beneficiaryAddress2 = '';
    this.beneficiaryAddress3 = '';
    this.city = '';
    this.locationId = '';
    this.stateId = '';
    this.countryId = '';
    this.pinCode = '';
    this.phoneNo = '';
    this.faxNo = '';
    this.email = '';
    this.paymentMethodId = '';
    this.debitCurrencyId = '';
    this.payableCurrencyId = '';
    this.corporateProductId = '';
    this.isPaperBasedTransaction = false;
    this.debitAmount = '';
    this.payableAmount = '';
    this.valueDate = '';
    this.transactionDate = '';
    this.debitAccountId = '';
    this.paymentDetails1 = '';
    this.paymentDetails2 = '';
    this.paymentDetails3 = '';
    this.paymentDetails4 = '';
    this.corporateRefNo = '';
    this.paymentType = '';
    this.amountType = 'PAYABLE';
    this.exchangeType = 'CARD';
    this.dealNo = '';
    this.forwardExchangeId = '';
    this.supportingDocList = [];
    this.enrichments = [];
    this.remarks = '';
    this.creditAccountId = '';
    this.creditCurrencyId = '';
    this.oatSiManagementAdditionalDetail = [new OatSiManagementAdditionalDetail()];
  }
}

export class OatSiManagementAdditionalDetail {
  public beneficiaryAccountNo?: string;
  public bicCodeId?: string;
  public bicCode?: string;
  public dispatchTo?: string;
  public instrumentDispatchMode?: string;
  public beneDispatchMode?: string;
  public remarks?: string;
  constructor() {
    this.beneficiaryAccountNo = '';
    this.bicCodeId = '';
    this.bicCode = '';
    this.dispatchTo = 'BENEFICIARY';
    this.instrumentDispatchMode = 'EMAIL';
    this.beneDispatchMode = '';
    this.remarks = '';
  }
}
